/*
 * Cafetería ITQ
 * API para la gestión de una cafetería.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: yop@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cafeland.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * RecipeItemsInner
 */
@JsonPropertyOrder({
  RecipeItemsInner.JSON_PROPERTY_SUPPLY_ID,
  RecipeItemsInner.JSON_PROPERTY_SUPPLY_NAME,
  RecipeItemsInner.JSON_PROPERTY_QUANTITY_NEEDED,
  RecipeItemsInner.JSON_PROPERTY_UNIT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-28T10:07:30.724146200-06:00[America/Mexico_City]")
public class RecipeItemsInner {
  public static final String JSON_PROPERTY_SUPPLY_ID = "supplyId";
  private String supplyId;

  public static final String JSON_PROPERTY_SUPPLY_NAME = "supplyName";
  private String supplyName;

  public static final String JSON_PROPERTY_QUANTITY_NEEDED = "quantityNeeded";
  private BigDecimal quantityNeeded;

  public static final String JSON_PROPERTY_UNIT = "unit";
  private String unit;

  public RecipeItemsInner() { 
  }

  public RecipeItemsInner supplyId(String supplyId) {
    this.supplyId = supplyId;
    return this;
  }

   /**
   * Get supplyId
   * @return supplyId
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_SUPPLY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSupplyId() {
    return supplyId;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSupplyId(String supplyId) {
    this.supplyId = supplyId;
  }


  public RecipeItemsInner supplyName(String supplyName) {
    this.supplyName = supplyName;
    return this;
  }

   /**
   * Get supplyName
   * @return supplyName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SUPPLY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSupplyName() {
    return supplyName;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplyName(String supplyName) {
    this.supplyName = supplyName;
  }


  public RecipeItemsInner quantityNeeded(BigDecimal quantityNeeded) {
    this.quantityNeeded = quantityNeeded;
    return this;
  }

   /**
   * Get quantityNeeded
   * @return quantityNeeded
  **/
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_QUANTITY_NEEDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getQuantityNeeded() {
    return quantityNeeded;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY_NEEDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantityNeeded(BigDecimal quantityNeeded) {
    this.quantityNeeded = quantityNeeded;
  }


  public RecipeItemsInner unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUnit() {
    return unit;
  }


  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnit(String unit) {
    this.unit = unit;
  }


  /**
   * Return true if this recipe_items_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipeItemsInner recipeItemsInner = (RecipeItemsInner) o;
    return Objects.equals(this.supplyId, recipeItemsInner.supplyId) &&
        Objects.equals(this.supplyName, recipeItemsInner.supplyName) &&
        Objects.equals(this.quantityNeeded, recipeItemsInner.quantityNeeded) &&
        Objects.equals(this.unit, recipeItemsInner.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplyId, supplyName, quantityNeeded, unit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipeItemsInner {\n");
    sb.append("    supplyId: ").append(toIndentedString(supplyId)).append("\n");
    sb.append("    supplyName: ").append(toIndentedString(supplyName)).append("\n");
    sb.append("    quantityNeeded: ").append(toIndentedString(quantityNeeded)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `supplyId` to the URL query string
    if (getSupplyId() != null) {
      joiner.add(String.format("%ssupplyId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSupplyId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `supplyName` to the URL query string
    if (getSupplyName() != null) {
      joiner.add(String.format("%ssupplyName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSupplyName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `quantityNeeded` to the URL query string
    if (getQuantityNeeded() != null) {
      joiner.add(String.format("%squantityNeeded%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQuantityNeeded()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `unit` to the URL query string
    if (getUnit() != null) {
      joiner.add(String.format("%sunit%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUnit()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

