/*
 * Cafetería ITQ
 * API para la gestión de una cafetería.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: yop@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cafeland.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * SuppliesSupplyIdPatchRequest
 */
@JsonPropertyOrder({
  SuppliesSupplyIdPatchRequest.JSON_PROPERTY_CANTIDAD_VARIACION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-28T10:07:30.724146200-06:00[America/Mexico_City]")
public class SuppliesSupplyIdPatchRequest {
  public static final String JSON_PROPERTY_CANTIDAD_VARIACION = "cantidad_variacion";
  private BigDecimal cantidadVariacion;

  public SuppliesSupplyIdPatchRequest() { 
  }

  public SuppliesSupplyIdPatchRequest cantidadVariacion(BigDecimal cantidadVariacion) {
    this.cantidadVariacion = cantidadVariacion;
    return this;
  }

   /**
   * Get cantidadVariacion
   * @return cantidadVariacion
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CANTIDAD_VARIACION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCantidadVariacion() {
    return cantidadVariacion;
  }


  @JsonProperty(JSON_PROPERTY_CANTIDAD_VARIACION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCantidadVariacion(BigDecimal cantidadVariacion) {
    this.cantidadVariacion = cantidadVariacion;
  }


  /**
   * Return true if this _supplies__supplyId__patch_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuppliesSupplyIdPatchRequest suppliesSupplyIdPatchRequest = (SuppliesSupplyIdPatchRequest) o;
    return Objects.equals(this.cantidadVariacion, suppliesSupplyIdPatchRequest.cantidadVariacion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cantidadVariacion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuppliesSupplyIdPatchRequest {\n");
    sb.append("    cantidadVariacion: ").append(toIndentedString(cantidadVariacion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `cantidad_variacion` to the URL query string
    if (getCantidadVariacion() != null) {
      joiner.add(String.format("%scantidad_variacion%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCantidadVariacion()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

