/*
 * Cafetería ITQ
 * API para la gestión de una cafetería.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: yop@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cafeland.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * SupplyInput
 */
@JsonPropertyOrder({
  SupplyInput.JSON_PROPERTY_SUPPLY_NAME,
  SupplyInput.JSON_PROPERTY_CURRENT_STOCK,
  SupplyInput.JSON_PROPERTY_UNIT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-28T10:07:30.724146200-06:00[America/Mexico_City]")
public class SupplyInput {
  public static final String JSON_PROPERTY_SUPPLY_NAME = "supplyName";
  private String supplyName;

  public static final String JSON_PROPERTY_CURRENT_STOCK = "currentStock";
  private Integer currentStock;

  /**
   * Gets or Sets unit
   */
  public enum UnitEnum {
    GR("gr"),
    
    ML("ml"),
    
    OZ("oz"),
    
    PZA("pza"),
    
    KG("kg"),
    
    L("L");

    private String value;

    UnitEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static UnitEnum fromValue(String value) {
      for (UnitEnum b : UnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_UNIT = "unit";
  private UnitEnum unit;

  public SupplyInput() { 
  }

  public SupplyInput supplyName(String supplyName) {
    this.supplyName = supplyName;
    return this;
  }

   /**
   * Get supplyName
   * @return supplyName
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=2)
  @JsonProperty(JSON_PROPERTY_SUPPLY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSupplyName() {
    return supplyName;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSupplyName(String supplyName) {
    this.supplyName = supplyName;
  }


  public SupplyInput currentStock(Integer currentStock) {
    this.currentStock = currentStock;
    return this;
  }

   /**
   * Cantidad actual en bodega
   * minimum: 0
   * @return currentStock
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(0)
  @JsonProperty(JSON_PROPERTY_CURRENT_STOCK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCurrentStock() {
    return currentStock;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_STOCK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrentStock(Integer currentStock) {
    this.currentStock = currentStock;
  }


  public SupplyInput unit(UnitEnum unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UnitEnum getUnit() {
    return unit;
  }


  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnit(UnitEnum unit) {
    this.unit = unit;
  }


  /**
   * Return true if this supplyInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupplyInput supplyInput = (SupplyInput) o;
    return Objects.equals(this.supplyName, supplyInput.supplyName) &&
        Objects.equals(this.currentStock, supplyInput.currentStock) &&
        Objects.equals(this.unit, supplyInput.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplyName, currentStock, unit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplyInput {\n");
    sb.append("    supplyName: ").append(toIndentedString(supplyName)).append("\n");
    sb.append("    currentStock: ").append(toIndentedString(currentStock)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `supplyName` to the URL query string
    if (getSupplyName() != null) {
      joiner.add(String.format("%ssupplyName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSupplyName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `currentStock` to the URL query string
    if (getCurrentStock() != null) {
      joiner.add(String.format("%scurrentStock%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCurrentStock()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `unit` to the URL query string
    if (getUnit() != null) {
      joiner.add(String.format("%sunit%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUnit()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

